// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/chat_message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4515869812050567965),
    name: 'ChatMessages',
    lastPropertyId: const obx_int.IdUid(6, 1070233151992812861),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6142807982565650428),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6388378791987321556),
        name: 'isFromMe',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1135518586066249206),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2723234422837266277),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5844680164934660079),
        name: 'time',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1070233151992812861),
        name: 'type',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 4515869812050567965),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessages: obx_int.EntityDefinition<ChatMessages>(
      model: _entities[0],
      toOneRelations: (ChatMessages object) => [],
      toManyRelations: (ChatMessages object) => {},
      getId: (ChatMessages object) => object.id,
      setId: (ChatMessages object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessages object, fb.Builder fbb) {
        final messageOffset = object.message == null
            ? null
            : fbb.writeString(object.message!);
        final imageOffset = object.image == null
            ? null
            : fbb.writeString(object.image!);
        final timeOffset = object.time == null
            ? null
            : fbb.writeString(object.time!);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        fbb.startTable(7);
        fbb.addOffset(0, messageOffset);
        fbb.addBool(1, object.isFromMe);
        fbb.addInt64(2, object.id ?? 0);
        fbb.addOffset(3, imageOffset);
        fbb.addOffset(4, timeOffset);
        fbb.addOffset(5, typeOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 4);
        final isFromMeParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final imageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final timeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final object = ChatMessages(
          message: messageParam,
          isFromMe: isFromMeParam,
          image: imageParam,
          type: typeParam,
          time: timeParam,
          id: idParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessages] entity fields to define ObjectBox queries.
class ChatMessages_ {
  /// See [ChatMessages.message].
  static final message = obx.QueryStringProperty<ChatMessages>(
    _entities[0].properties[0],
  );

  /// See [ChatMessages.isFromMe].
  static final isFromMe = obx.QueryBooleanProperty<ChatMessages>(
    _entities[0].properties[1],
  );

  /// See [ChatMessages.id].
  static final id = obx.QueryIntegerProperty<ChatMessages>(
    _entities[0].properties[2],
  );

  /// See [ChatMessages.image].
  static final image = obx.QueryStringProperty<ChatMessages>(
    _entities[0].properties[3],
  );

  /// See [ChatMessages.time].
  static final time = obx.QueryStringProperty<ChatMessages>(
    _entities[0].properties[4],
  );

  /// See [ChatMessages.type].
  static final type = obx.QueryStringProperty<ChatMessages>(
    _entities[0].properties[5],
  );
}
